### PR TITLE
Updating nightmare fixing 'timeout exceeded'

### PR DESCRIPTION
**Pull request by falconscript**
Duplicate include referencing pull request from nightmare-google-oauth2: https://github.com/h2non/nightmare-google-oauth2/pull/11

### CODE REVIEW

**Comment by falconscript** [comment]
Thanks for the prompt merges! Please remember to update the npm versions in package.json for this and the oauth module, as well as update the oauth module's version in this repository, then to npm publish

Thanks

**Comment by h2non** [comment]
yeah, working on that. will let you know once done.

**Comment by h2non** [comment]
`youtube-video-api@0.3.7` is now available via `npm` registry!

**Comment by h2non** [comment]
typo: `not` -> `now` :)

**Comment by falconscript** [comment]
Thanks man

**Pull request merged**
